TEST_SSH_PRIVATE_KEY: ENC[AES256_GCM,data:Ej+hnSZCoiYDJvFUQCvpQfTHYmUAc4nTlm2bjLla/av1XFye4efBlO7UnLZTpQhd234jreMLJ5ux7qeDib9pAD9SUtP1PJJVRSdZF8b49FUvLcGp20ppm6Yhv1EMzj/7NIVSOSJZDZrGWdAJfMV8gCqBDhewb0NW9wuZUZiUfdvcw3L/wxb1m3fRrAE2/uri1KUooTzeZah+TyrX6+tMUqHkPl7cOpNFXk3XUXHCo8F1mwgw5qGjaCVBTn2MzwL1ggeXpvI9SHJoqASJOuhjgnVbM37eS88Wuy+cRMKD13Fhq35oFCrsni7/VYPtHA9wX+0TOecthcK5jvUPI32o2gQxqzNvSWbCnme/p4W94/UR53L7aJ4G3OZp3a5WHUmg9S+So+rd0wNydS7MAAmcMWlxcH0q1eZC8mtNEHM1Qp589h2lA0ssIND3GHsrvwcXuSDOAFpuIJniTQ22cITJqq0KttHHiXzw68QvhMI5EOEDj/F1Vncx4UCl+4mjjCL5yarlqjXMuiOVSnaJHVHRrnQTbuaXPQj7d7qiFST3Dj2gsynctjglNIaYgF49OzOrpoV+Jy9ng6FAwvg944S4w4CdCmzosdVzqo4H2g2XAnGpKHMejVq7GpM8i8vIHtJNexo/IonD27ol7dQPdXqKwD1EQlcEbRGnjg==,iv:RL5S0FhI86ecy/cOxfdaBZc+h1eLYBwaZzvsgZQ3lNI=,tag:TdnSN83ZtJIuNHmM6ZwMAA==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSjhhWWxIZHlGM09BS1M2
            bW5QVkZJR0UxeFlzMmZEek9CYXZDY0V6MVJFCnpSVy9ob2wvY003SFkydW80Qm9X
            MDFSb0l0Vnp2T09XUlhaYnNVZFFuRjAKLS0tIDRjTlM5YlJ0RnFNY0tTV1hJcmN4
            RnNZNDVUOUFUUkZGcjhLTWd4aDhtbDgKQd6YZ0MeUlcYG9vI2VE46WZqhfr8vby4
            oogfn02TxDDj79LuD+Ud7KAAbCPX2XI2F0J71IBei5V9j9HaLRQrlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T07:04:02Z"
    mac: ENC[AES256_GCM,data:FjrUfeC/cCqp0ncDmkvUw658bqliuqC9U2i7HiBFYUO2iE22mqtC9sT0AQwKUc657Gz9OMLHGVOtdN1pgxwI8PaMv8zXxdKPOryyhoXbkHiAukB5Od4jSyH0NdHkGVWZHbcxDoxlL6+h/d5cmVxlHDcPeys1MtjFNRXm5kvhMkg=,iv:T1zeSwXW8k1cJevXKLl6wC+cTEfdVJS7niLLKO3vc6s=,tag:73pmfezNCBidIG2bPzrD3g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
