[tools]
dagger = "0.19.3"

[env]
PROJECT_NAME = "{{ config_root | basename }}"

[hooks]
enter = [
  'echo ""',
  'echo "[MISE] Setup $PROJECT_NAME project..."',
  #
  'mise i -q',
  #
  'pre-commit install',
]
