[tools]
dagger = "0.19.3"

[env]
PROJECT_NAME = "{{ config_root | basename }}"

[hooks]
enter = [
  'echo ""',
  'echo "[MISE] Setup $PROJECT_NAME project..."',
  #
  'mise i -q',
  #
  'pre-commit install',
  #
  'echo "$TEST_SSH_PRIVATE_KEY" > ansible/tests/test-data/test_id_ecdsa',
  'chmod 600 ansible/tests/test-data/test_id_ecdsa'
]
