[tools]
dagger = "0.19.3"

# [settings]
# python.uv_venv_auto = true

# [hooks]
# enter = "uv pip install -q -r requirements.txt"

# [tasks.install-deps]
# description = "Install Python dependencies"
# run = "uv pip install -r requirements.txt"

# [env]
# _.file = [
#   { path = "{{env.HOME}}/.env", optional = true },
#   { path = ".env", optional = true },
#   { path = ".creds.env.yaml", redact = true }
# ]
# _.python.venv = { path = ".venv", create = true }
